CREATE TABLE PRODUCTS_SHAKIR
(
ProductID INT PRIMARY KEY,
ProductName VARCHAR(100),
ProductPrice FLOAT
)


CREATE TABLE ORDERS_SHAKIR
(
OrderID INT PRIMARY KEY,
CustomerID INT,
OrderDate DATE,
ProductID INT
)


ALTER TABLE ORDERS_SHAKIR ADD CONSTRAINT Fk_CID FOREIGN KEY (CustomerID) REFERENCES EMP_SHAKIR(EmpID)

ALTER TABLE ORDERS_SHAKIR ADD CONSTRAINT Fk_PID FOREIGN KEY (ProductID) REFERENCES PRODUCTS_SHAKIR(ProductID)


INSERT INTO PRODUCTS_SHAKIR
SELECT 1,'CANON EOS 1200',25000 UNION ALL
SELECT 2,'IPHONE X',89000 UNION ALL
SELECT 3,'LEVIS SHIRT',1500 UNION ALL
SELECT 4,'LOGITECH MOUSE',500 UNION ALL
SELECT 5,'OPPO F11',18000 UNION ALL
SELECT 6,'TEMPERED GLASS',200 UNION ALL
SELECT 7,'GUCCI SUNGLASSES',6000 UNION ALL
SELECT 8,'LAPTOP',50000 UNION ALL
SELECT 9,'REEBOK SHOES',3000 UNION ALL
SELECT 10,'ZARA JEANS',4000 


SELECT * FROM PRODUCTS_SHAKIR


SELECT * FROM ORDERS_SHAKIR


ALTER TABLE PRODUCTS_SHAKIR ADD ProductsQty int 


UPDATE PRODUCTS_SHAKIR

SET    ProductsQty =

       CASE ProductID

            WHEN 1 THEN 10

            WHEN 2 THEN 5

            WHEN 3 THEN 4

            WHEN 4 THEN 20

            WHEN 5 THEN 9

            WHEN 6 THEN 7

            WHEN 7 THEN 10

            WHEN 8 THEN 11

            WHEN 9 THEN 15
			
		    WHEN 10 THEN 8

       END

WHERE  ProductID IN (1,2,3,4,5,6,7,8,9,10);



INSERT INTO ORDERS_SHAKIR
SELECT 1,1,GETDATE(),1 UNION ALL
SELECT 2,1,GETDATE(),2 UNION ALL
SELECT 3,1,GETDATE(),3 UNION ALL
SELECT 4,2,GETDATE(),4 UNION ALL
SELECT 5,2,GETDATE(),5 UNION ALL
SELECT 6,2,GETDATE(),6 UNION ALL
SELECT 7,3,GETDATE(),7 UNION ALL
SELECT 8,3,GETDATE(),8 UNION ALL
SELECT 9,3,GETDATE(),9 UNION ALL
SELECT 10,4,GETDATE(),10 UNION ALL
SELECT 11,4,GETDATE(),1 UNION ALL
SELECT 12,5,GETDATE(),2 UNION ALL
SELECT 13,5,GETDATE(),3 UNION ALL
SELECT 14,5,GETDATE(),4 UNION ALL
SELECT 15,5,GETDATE(),5 UNION ALL
SELECT 16,6,GETDATE(),6 UNION ALL
SELECT 17,7,GETDATE(),7 UNION ALL
SELECT 18,7,GETDATE(),8 UNION ALL
SELECT 19,8,GETDATE(),9 UNION ALL
SELECT 20,8,GETDATE(),10 UNION ALL
SELECT 21,8,GETDATE(),1 UNION ALL
SELECT 22,9,GETDATE(),2 UNION ALL
SELECT 23,9,GETDATE(),3 UNION ALL
SELECT 24,9,GETDATE(),4 UNION ALL
SELECT 25,9,GETDATE(),5 UNION ALL
SELECT 26,9,GETDATE(),6 UNION ALL
SELECT 27,9,GETDATE(),7 UNION ALL
SELECT 28,9,GETDATE(),8 UNION ALL
SELECT 29,9,GETDATE(),9 UNION ALL
SELECT 30,9,GETDATE(),10 UNION ALL
SELECT 31,9,GETDATE(),1 UNION ALL
SELECT 32,9,GETDATE(),2 UNION ALL
SELECT 33,10,GETDATE(),3 UNION ALL
SELECT 34,11,GETDATE(),4 UNION ALL
SELECT 35,11,GETDATE(),5 UNION ALL
SELECT 36,11,GETDATE(),6

--INNER JOIN OF ORDERS PRODUCTS AND EMPLOYEES 
SELECT * 
FROM ORDERS_SHAKIR O
INNER JOIN EMP_SHAKIR E ON O.CustomerID=E.EmpID
INNER JOIN PRODUCTS_SHAKIR P ON O.ProductID=P.ProductID

--SUM OF PRICE OF ALL ORDERS
SELECT SUM(ProductPrice)
FROM ORDERS_SHAKIR O
INNER JOIN EMP_SHAKIR E ON O.CustomerID=E.EmpID
INNER JOIN PRODUCTS_SHAKIR P ON O.ProductID=P.ProductID

--AVERAGE PRICE OF EACH ORDER
SELECT AVG(ProductPrice)
FROM ORDERS_SHAKIR O
INNER JOIN EMP_SHAKIR E ON O.CustomerID=E.EmpID
INNER JOIN PRODUCTS_SHAKIR P ON O.ProductID=P.ProductID

--TOTAL NUMBER OF ORDERS
SELECT COUNT(OrderID)
FROM ORDERS_SHAKIR O
INNER JOIN EMP_SHAKIR E ON O.CustomerID=E.EmpID
INNER JOIN PRODUCTS_SHAKIR P ON O.ProductID=P.ProductID


--SUM OF PRICE OF ALL ORDERS CUSTOMER WISE
SELECT E.EmpName,SUM(ProductPrice)
FROM ORDERS_SHAKIR O
INNER JOIN EMP_SHAKIR E ON O.CustomerID=E.EmpID
INNER JOIN PRODUCTS_SHAKIR P ON O.ProductID=P.ProductID
GROUP BY E.EmpName


--COUNT OF PRODUCTS ORDERED PRODUCT WISE
SELECT P.ProductName,COUNT(O.ProductID)
FROM ORDERS_SHAKIR O
INNER JOIN EMP_SHAKIR E ON O.CustomerID=E.EmpID
INNER JOIN PRODUCTS_SHAKIR P ON O.ProductID=P.ProductID
GROUP BY P.ProductName


--TOTAL NO OF PRODUCTS ORDERED CUSTOMER WISE
SELECT E.EmpName,COUNT(OrderID)
FROM ORDERS_SHAKIR O
INNER JOIN EMP_SHAKIR E ON O.CustomerID=E.EmpID
INNER JOIN PRODUCTS_SHAKIR P ON O.ProductID=P.ProductID
GROUP BY E.EmpName



--PRODUCTS WHOSE QUANTITY IS MORE THAN 10
SELECT * FROM PRODUCTS_SHAKIR
WHERE ProductsQty>10



--SUM OF PRICE OF ALL ORDERS PRODUCT WISE
SELECT P.ProductName,P.ProductPrice,COUNT(P.ProductName),SUM(ProductPrice) 
FROM ORDERS_SHAKIR O
INNER JOIN EMP_SHAKIR E ON O.CustomerID=E.EmpID
INNER JOIN PRODUCTS_SHAKIR P ON O.ProductID=P.ProductID
GROUP BY P.ProductName,P.ProductPrice





